name: CI

on:
  push:
    branches: [default]
  pull_request:
    branches: [default]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build Rust
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Check code style
        run: cargo clippy
